name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t tienanhknock/action-be .
      - name: Publish image to docker hub
        run: docker push tienanhknock/action-be
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull tienanhknock/action-be
      - name: Delete old container
        run: docker rm -f lulbe1
      - name: Run docker container
        run: docker run --rm -p 80:80 --name lulbe1 -e LISTENING_PORT=80 -d tienanhknock/action-be
        