name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t tienanhknock/action-be .
      - name: Publish image to docker hub
        run: docker push tienanhknock/action-be
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull tienanhknock/action-be
      - name: Delete old container
        run: docker rm -f lulbe1
      - name: Delete old container
        run: docker rm -f lulbe2
      - name: Delete old container
        run: docker rm -f nginx-docker
      - name: Delete old network
        run: docker network rm -f lul-net
      - name: Delete old nginx
        run:  'if docker volume ls | grep -q nginx.conf; then
                docker volume remove nginx.conf
              else
                echo "nginx-conf not exist."
              fi'
              
      - name: Pull image from docker hub
        run: docker pull tienanhknock/action-be
      - name: Create network
        run: docker network create lul-net
      - name: Run docker container
        run: docker run --rm --name lulbe1 --hostname lulbe1 --network lul-net -e LISTENING_PORT=8090 -d tienanhknock/action-be
      - name: Run docker container
        run: docker run --rm --name lulbe2 --hostname lulbe2 --network lul-net -e LISTENING_PORT=8090 -d tienanhknock/action-be
      - name: Run docker container
        run: docker run --rm --name nginx-docker --network lul-net -p 80:8090 -d -v /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf nginx
        